# Codecademy - CS102: Data Structures and Algorithms - Final Project
# Flower types include colors, life cycles, seasons, toxicity, and names (from data list) and flower data
# includes this information for every flower (FTD. (2014). _Flower Color Identification Guide_. https://www.ftd.com/blog/flower-identification-guide-by-color;
# ASPCA. (2022). _Poisonous Plants: Toxic and Non-Toxic Plants List_. https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants;
# ProFlowers. (2017). _Types of Flowers by Color_. https://www.proflowers.com/blog/types-flower-color)

flower_types = ['red', 'orange', 'yellow', 'green', 'blue', 'purple', 'pink', 'white', 'black', 
                'perennial', 'annual', 'biennial', 'winter', 'spring', 'summer', 'fall', 'safe']

flower_data = [['chrysanthemum', 'fall', 'perennial/annual', 'red, orange, yellow, green, purple, pink, white'],
               ['marigold', 'summer/fall', 'perennial/annual', 'red, orange, yellow, pink, white'],
               ['alstroemeria', 'summer', 'perennial', 'red, orange, yellow, green, purple, pink, white'],
               ['anemone', 'spring/summer/fall', 'perennial', 'red, orange, yellow, blue, purple, pink, white'],
               ['zinnia', 'summer/fall', 'annual', 'red, orange, yellow, green, purple, pink, white', 'safe'],
               ['poppy', 'spring/summer', 'perennial/annual/biennial', 'red, orange, yellow, blue, purple, pink, white'],
               ['rose', 'spring/summer/fall', 'perennial', 'red, orange, yellow, green, blue, purple, pink, white, black', 'safe'],
               ['lily', 'summer', 'perennial', 'red, orange, yellow, purple, pink, white, black'],
               ['calla lily', 'spring/summer', 'perennial', 'red, orange, yellow, green, purple, pink, white, black'],
               ['tulip', 'spring', 'perennial', 'red, orange, yellow, green, purple, pink, white, black'],
               ['carnation', 'spring', 'perennial', 'red, orange, yellow, green, purple, pink, white'],
               ['gerbera daisy', 'spring/summer/fall', 'perennial/annual', 'red, orange, yellow, green, purple, pink, white', 'safe'],
               ['cockscomb', 'summer/fall', 'perennial/annual', 'red, orange, yellow, green, purple, pink, white', 'safe'],
               ['peony', 'spring/summer', 'perennial', 'red, orange, yellow, green, purple, pink, white'],
               ['dianthus', 'spring/summer', 'perennial/annual/biennial', 'red, orange, yellow, purple, pink, white, black'],
               ['begonia', 'spring/summer', 'perennial/annual', 'red, orange, yellow, pink, white'],
               ['pentas', 'summer', 'perennial/annual', 'red, orange, purple, pink, white', 'safe'],
               ['dahlia', 'summer/fall', 'perennial/annual', 'red, orange, yellow, green, purple, pink, white, black'],
               ['columbine', 'spring/summer', 'perennial', 'red, orange, yellow, blue, purple, pink, white'],
               ['camellia', 'fall/winter/spring', 'perennial', 'red, orange, pink, white', 'safe'],
               ['sunflower', 'summer/fall', 'annual', 'red, orange, yellow, purple, pink, white', 'safe'],
               ['hibiscus', 'summer', 'perennial', 'red, orange, yellow, purple, pink, white'],
               ['geranium', 'spring/summer/fall', 'perennial/annual/biennial', 'red, orange, yellow, blue, purple, pink, white', 'safe'],
               ['azalea', 'spring/summer/fall', 'perennial/annual', 'red, orange, yellow, purple, pink, white'],
               ['amaranthus', 'summer/fall', 'perennial/annual', 'red, orange, yellow, green, purple, pink'],
               ['salvia', 'spring/summer/fall', 'perennial', 'red, orange, blue, purple, pink, white', 'safe'],
               ['streptocarpus', 'spring/summer', 'perennial', 'red, purple, pink, white', 'safe'],
               ['sweet pea', 'spring/summer', 'annual', 'red, orange, blue, purple, pink, white'],
               ['cosmos', 'summer/fall', 'perennial/annual', 'red, orange, yellow, purple, pink, white', 'safe'],
               ['hyacinth', 'spring', 'perennial', 'red, orange, blue, purple, pink, white, black'],
               ['canna', 'summer', 'perennial', 'red, orange, yellow, pink, white', 'safe'],
               ['clematis', 'summer/fall', 'perennial', 'red, blue, purple, pink, white'],
               ['coneflower', 'summer', 'perennial', 'red, orange, yellow, green, purple, pink, white', 'safe'],
               ['gloxinia', 'summer/fall', 'perennial/annual', 'red, purple, pink, white', 'safe'],
               ['hellebore', 'winter/spring', 'perennial', 'red, orange, yellow, green, purple, pink, white, black'],
               ['lycoris', 'summer/fall', 'perennial', 'red, orange, yellow, pink, white'],
               ['verbena', 'spring/summer', 'perennial', 'red, purple, pink, white'],
               ['daylily', 'spring/summer', 'perennial', 'red, orange, yellow, green, purple, pink, white'],
               ['ranunculus', 'winter/spring', 'perennial/annual', 'red, orange, yellow, green, purple, pink, white'],
               ['aster', 'summer/fall', 'perennial', 'red, orange, yellow, purple, pink, white'],
               ['yarrow', 'summer/fall', 'perennial', 'red, orange, yellow, purple, pink, white'],
               ['orchid', 'fall/winter/spring', 'perennial', 'red, orange, yellow, green, purple, pink, white, black'],
               ['freesia', 'spring/summer', 'perennial', 'red, orange, yellow, blue, purple, pink, white', 'safe'],
               ['petunia', 'spring', 'perennial', 'red, yellow, green, blue, purple, pink, white, black', 'safe'],
               ['anthurium', 'spring/summer/fall', 'perennial', 'red, orange, yellow, green, purple, pink, white, black'],
               ['cardinal', 'summer', 'perennial', 'red'],
               ['gaillardia', 'summer/fall', 'perennial', 'red, orange, yellow, pink, white'],
               ['scarlet beebalm', 'summer', 'perennial', 'red, purple, pink, white', 'safe'],
               ['hydrangea', 'spring/summer/fall', 'perennial', 'red, orange, yellow, green, blue, purple, pink, white'],
               ['black eyed susan', 'summer/fall', 'perennial/biennial', 'red, orange, yellow', 'safe'],
               ['hollyhock', 'summer/fall', 'perennial/biennial', 'red, orange, yellow, blue, purple, pink, white, black'],
               ['pansy', 'spring/fall', 'perennial/biennial', 'red, orange, yellow, green, blue, purple, pink, white, black'],
               ['sweet william', 'spring/summer', 'perennial/biennial', 'red, orange, yellow, green, purple, pink, white'],
               ['wallflower', 'spring/summer/fall', 'perennial/biennial', 'red, orange, yellow, green, blue, purple, pink, white'],
               ['bird of paradise', 'winter/spring', 'perennial', 'red, orange, yellow, blue, purple, white'],
               ['iris', 'spring/summer', 'perennial', 'red, orange, yellow, blue, purple, pink, white, black'],
               ['lantana', 'spring/summer/fall', 'perennial', 'red, orange, yellow, purple, pink, white'],
               ['crown imperial', 'spring', 'perennial', 'red, orange, yellow'],
               ['helenium', 'summer/fall', 'perennial', 'red, orange, yellow'],
               ['butterfly weed', 'summer/fall', 'perennial', 'red, orange, yellow'],
               ['cymbidium orchid', 'fall/winter/spring', 'perennial', 'red, orange, yellow, green, purple, pink, white', 'safe'],
               ['plumeria', 'summer', 'perennial', 'red, orange, yellow, purple, pink, white'],
               ['primrose', 'winter/spring', 'perennial/annual', 'red, orange, yellow, green, blue, purple, pink, white'],
               ['gladiolus', 'summer/fall', 'perennial', 'red, orange, yellow, green, purple, pink, white'],
               ['spider mum', 'fall', 'perennial', 'red, orange, yellow, green, purple, pink, white'],
               ['scabiosa', 'summer', 'perennial', 'red, yellow, green, blue, purple, pink, white, black', 'safe'],
               ['lupine', 'spring/summer', 'perennial/annual', 'red, orange, yellow, blue purple, pink, white'],
               ['bellflower', 'spring/summer/fall', 'perennial', 'red, blue, purple, pink, white', 'safe'],
               ['bell heather', 'winter', 'perennial', 'red, purple, pink, white'],
               ['plume thistle', 'summer', 'perennial', 'red'],
               ['candytuft', 'spring/summer', 'perennial', 'red, purple, pink, white'],
               ['cyclamen', 'fall/winter/spring', 'perennial', 'red, purple, pink, white'],
               ['crocus', 'spring/fall', 'perennial', 'red, orange, yellow, purple, pink, white'],
               ['dendrobium orchid', 'winter/spring', 'perennial', 'red, orange, yellow, green, purple, pink, white', 'safe'],
               ['fuchsia', 'spring/summer/fall', 'perennial', 'red, orange, yellow, purple, pink, white, black', 'safe'],
               ['lisianthus', 'summer/fall', 'perennial/annual/biennial', 'red, yellow, green, purple, pink, white', 'safe'],
               ['morning glory', 'summer/fall', 'perennial', 'red, orange, yellow, blue purple, pink, white'],
               ['pasque', 'spring', 'perennial', 'red, purple, pink, white'],
               ['rhododendron', 'spring/summer', 'perennial', 'red, orange, yellow, purple, pink, white'],
               ['sedum', 'summer/fall', 'perennial', 'red, yellow, purple, pink, white', 'safe'],
               ['coreopsis', 'summer/fall', 'perennial', 'red, orange, yellow, purple, pink, white', 'safe'],
               ['snapdragon', 'spring/summer/fall', 'perennial/annual', 'red, orange, yellow, purple, pink, white', 'safe'],
               ['bouvardia', 'summer/fall', 'perennial', 'red, orange, pink, white'],
               ['periwinkle', 'spring/summer/fall', 'perennial', 'red, yellow, blue, purple, pink, white'],
               ['daisy', 'spring/summer', 'perennial/annual', 'red, orange, yellow, blue, purple, pink, white'],
               ['phlox', 'summer', 'perennial/annual', 'red, orange, yellow, purple, pink, white', 'safe'],
               ['queen anne\'s lace', 'summer', 'biennial', 'red, pink, white'],
               ['tuberose', 'summer', 'perennial', 'red, orange, yellow, purple, pink, white'],
               ['astilbe', 'spring/summer', 'perennial', 'red, purple, pink, white', 'safe'],
               ['crepe myrtle', 'spring/summer', 'perennial', 'red, purple, pink, white', 'safe'],
               ['crabapple', 'spring', 'perennial', 'red, pink, white'],
               ['impatiens', 'spring/summer', 'perennial/annual', 'red, orange, yellow, blue, purple, pink, white'], 
               ['violet', 'winter/spring', 'perennial', 'red, orange, yellow, blue, purple, pink, white', 'safe'], 
               ['viola', 'spring/fall', 'perennial', 'red, orange, yellow, blue, purple, pink, white, black'],
               ['water lily', 'spring/summer', 'perennial', 'red, orange, yellow, blue, purple, pink, white'],
               ['cornflower', 'summer', 'annual', 'red, blue, purple, pink, white'],
               ['lungwort', 'spring', 'perennial', 'red, blue, purple, pink, white'],
               ['lobelia', 'summer/fall', 'perennial', 'red, blue, purple, pink, white'],
               ['bulbine', 'spring/summer/fall', 'perennial', 'orange, yellow'],
               ['lion\'s tail', 'spring/summer', 'perennial', 'orange, yellow'],
               ['red hot poker', 'spring/summer/fall', 'perennial', 'orange, yellow, green'],
               ['pincushion protea', 'summer', 'perennial/biennial', 'orange, yellow, pink, white'],
               ['daffodil', 'winter/spring', 'perennial', 'orange, yellow, pink, white'],
               ['butterfly bush', 'summer', 'perennial', 'orange, yellow, blue, purple, pink, white'],
               ['scarlet pimpernel', 'spring/summer', 'annual', 'orange, blue'],
               ['jessamine', 'winter/spring', 'perennial', 'yellow'],
               ['goldenrod', 'summer/fall', 'perennial', 'yellow'],
               ['craspedia', 'spring/summer', 'perennial', 'yellow'],
               ['ausmas', 'spring/summer/fall', 'perennial', 'yellow'],
               ['golden columbine', 'spring/summer', 'perennial', 'yellow'],
               ['corydalis', 'spring/summer', 'perennial', 'yellow, blue, purple, pink, white'],
               ['wild indigo', 'spring/summer', 'perennial', 'yellow, blue, purple, white'],
               ['allium', 'spring/summer', 'perennial', 'yellow, blue, purple, pink, white'],
               ['blue eyed grass', 'spring/summer', 'perennial', 'yellow, blue, purple, white'],
               ['grape hyacinth', 'spring', 'perennial', 'yellow, blue, purple, pink, white'],
               ['magnolia', 'spring/summer', 'perennial', 'yellow, purple, pink, white'],
               ['forsythia', 'spring', 'perennial', 'yellow'],
               ['sweet alyssum', 'spring/fall', 'perennial/annual', 'yellow, purple, pink, white'],
               ['thistle', 'summer', 'perennial', 'yellow, blue, purple, pink, white'],
               ['jasmine', 'winter/spring', 'perennial', 'yellow, pink, white'],
               ['gardenia', 'spring/summer', 'perennial', 'yellow, white'],
               ['bells of ireland', 'summer', 'annual', 'green'],
               ['sea holly', 'summer/fall', 'perennial', 'green, blue, purple, white'],
               ['globe thistle', 'summer', 'perennial', 'blue, purple, white'],
               ['forget me not', 'spring/summer', 'perennial', 'blue, purple, pink, white'],
               ['gentian', 'spring/summer/fall', 'perennial', 'blue, purple, white'],
               ['brunnera', 'spring/summer', 'perennial', 'blue, purple'],
               ['bluestar', 'spring/summer', 'perennial', 'blue, purple, white'],
               ['georgia blue', 'spring', 'perennial', 'blue, purple'],
               ['agapanthus', 'spring/summer', 'perennial', 'blue, purple, white'],
               ['bluebeard', 'summer/fall', 'perennial', 'blue, purple'],
               ['love in a mist', 'spring/summer', 'annual', 'blue, purple, pink, white'],
               ['siberian squill', 'winter/spring', 'perennial', 'blue, purple, white'],
               ['veronica', 'summer', 'perennial/annual', 'blue, purple, pink, white'],
               ['glory of the snow', 'winter/spring', 'perennial', 'blue, purple, pink, white'],
               ['birdbill dayflower', 'summer/fall', 'perennial', 'blue, purple'],
               ['bluecrown passionflower', 'summer/fall', 'perennial', 'blue, purple, pink, white'],
               ['tufted lily', 'spring/summer', 'perennial', 'blue, purple, white'],
               ['balloon flower', 'summer', 'perennial', 'blue, purple, pink, white'],
               ['wild hyacinth', 'spring/summer', 'perennial', 'blue, purple, pink, white'],
               ['canterbury bells', 'summer', 'perennial/biennial', 'blue, purple, pink, white'],
               ['wisteria', 'spring/summer', 'perennial', 'blue, purple, pink, white'],
               ['comfrey', 'spring/summer', 'perennial', 'blue, purple, pink, white'],
               ['lavender', 'spring/summer', 'perennial', 'purple, pink, white'],
               ['catmint', 'spring/summer/fall', 'perennial', 'purple, pink, white'],
               ['alpine betony', 'summer', 'perennial', 'purple, pink'],
               ['waxflower', 'winter/spring', 'perennial', 'purple, pink, white'],
               ['heliotrope', 'summer/fall', 'perennial', 'purple, pink, white'],
               ['honesty', 'spring/summer', 'perennial/biennial', 'purple, pink, white'],
               ['liatris', 'summer', 'perennial', 'purple, pink, white'],
               ['lilac', 'spring/summer', 'perennial', 'purple, pink, white'],
               ['mystic merlin', 'summer/fall', 'perennial/biennial', 'purple, pink, white'],
               ['moonflower', 'summer', 'perennial', 'purple, white'],
               ['rose gentian', 'summer', 'perennial/biennial', 'purple, pink'],
               ['redbud', 'spring', 'perennial', 'purple, pink, white'],
               ['bat flower', 'summer/fall', 'perennial', 'purple, black'],
               ['baby\'s breath', 'summer', 'perennial/annual', 'pink, white'],
               ['yucca', 'summer/fall', 'perennial', 'pink, white'],
               ['cherry blossom', 'spring', 'perennial', 'pink, white'],
               ['dogwood', 'spring', 'perennial', 'pink, white'],
               ['snowdrop', 'winter/spring/fall', 'perennial', 'white'],
               ['star of bethlehem', 'spring/summer', 'perennial', 'white'],
               ['stephanotis', 'spring/summer', 'perennial', 'white']]